### ISSUE TITLE
APIを繋ぐことへの検討

### ISSUE THREAD

**Issue by ktaroabobon** [ktaroabobon/ifcjs-react#11]
- [x] ボタンをAPIへ繋ぎ、IFCデータを送信する（lzmaで圧縮）
- [ ] 受け取ったデータをjsonとしてダウンロードする

**Comment by ktaroabobon** [comment]
#7 のうちの一つ

**Comment by ktaroabobon** [comment]
一旦目標を
- a

**Comment by ktaroabobon** [comment]
- [ ] ボタンをAPIへ繋ぎ、IFCデータを送信する（lzmaで圧縮）
- [ ] 受け取ったデータをjsonとしてダウンロードする

**Comment by ktaroabobon** [comment]
ifcの圧縮についてはbackend側にてlzmaを使用していたが、frontendで使えそうなパッケージが見つからない。

そこで、frontendでもbackendでも使用可能な以下のパッケージを使うのは有用であるかもしれない。圧縮率はどの程度かはわからない。

**Comment by ktaroabobon** [comment]
https://github.com/pieroxy/lz-string

**Comment by ktaroabobon** [comment]
一旦lzma-nativeで進める

**Comment by ktaroabobon** [comment]
インストールしたパッケージ

```bash
yarn add lzma-native
yarn add --dev @types/lzma/native
yarn add events
```

**Comment by ktaroabobon** [comment]
次なるエラー

```bash
browser-external:buffer:9 Uncaught Error: Module "buffer" has been externalized for browser compatibility. Cannot access "buffer.Buffer" in client code.
    at Object.get (browser-external:buffer:9:13)
    at node_modules/readable-stream/lib/_stream_readable.js (_stream_readable.js:46:14)
    at __require2 (chunk-S5KM4IGW.js?v=4dfeee9e:18:50)
    at node_modules/readable-stream/readable-browser.js (readable-browser.js:1:28)
    at __require2 (chunk-S5KM4IGW.js?v=4dfeee9e:18:50)
    at index.js:4:14
    at node_modules/lzma-native/index.js (index.js:595:1)
    at __require2 (chunk-S5KM4IGW.js?v=4dfeee9e:18:50)
    at dep:lzma-native:1:16
```

**Comment by ktaroabobon** [comment]
```bash
yarn add buffer
```
をする

**Comment by ktaroabobon** [comment]
次なるエラー

```bash
Uncaught ReferenceError: global is not defined
    at node_modules/readable-stream/lib/_stream_readable.js (_stream_readable.js:48:21)
    at __require2 (chunk-S5KM4IGW.js?v=07fc75eb:18:50)
    at node_modules/readable-stream/readable-browser.js (readable-browser.js:1:28)
    at __require2 (chunk-S5KM4IGW.js?v=07fc75eb:18:50)
    at index.js:4:14
    at node_modules/lzma-native/index.js (index.js:595:1)
    at __require2 (chunk-S5KM4IGW.js?v=07fc75eb:18:50)
    at dep:lzma-native:1:16
```

**Comment by ktaroabobon** [comment]
https://github.com/vitejs/vite/discussions/5912

**Comment by ktaroabobon** [comment]
次なるエラー

```bash
browser-external:util:9 Uncaught Error: Module "util" has been externalized for browser compatibility. Cannot access "util.debuglog" in client code.
    at Object.get (browser-external:util:9:13)
    at node_modules/readable-stream/lib/_stream_readable.js (_stream_readable.js:64:28)
    at __require2 (chunk-S5KM4IGW.js?v=0ec91873:18:50)
    at node_modules/readable-stream/readable-browser.js (readable-browser.js:1:28)
    at __require2 (chunk-S5KM4IGW.js?v=0ec91873:18:50)
    at index.js:4:14
    at node_modules/lzma-native/index.js (index.js:595:1)
    at __require2 (chunk-S5KM4IGW.js?v=0ec91873:18:50)
    at dep:lzma-native:1:16
```

**Comment by ktaroabobon** [comment]
```bash
yarn add util
```
を追加

**Comment by ktaroabobon** [comment]
lzma-nativeやめる

**Comment by ktaroabobon** [comment]
lzmaではないアルゴリズムを使って送受信する

**Comment by ktaroabobon** [comment]
https://github.com/ktaroabobon/ifc-bc/issues/12

**Comment by ktaroabobon** [comment]
gzipで試してみる

**Comment by ktaroabobon** [comment]
https://service.plan-b.co.jp/blog/tech/10282/

**Comment by ktaroabobon** [comment]
```bash
yarn add lz4
yarn add --dev @types/lz4
```

https://github.com/pierrec/node-lz4

**Comment by ktaroabobon** [comment]
lz4むりそう

**Comment by ktaroabobon** [comment]
gzipでやります

**Comment by ktaroabobon** [comment]
https://qiita.com/yoshiweb/items/b46de8ca85bb59921f67

**Comment by ktaroabobon** [comment]
なんかできない

**Comment by ktaroabobon** [comment]
lz-stringでやってみる

**Comment by ktaroabobon** [comment]
https://github.com/pieroxy/lz-string

```bash
yarn add lz-string
yarn add --dev @types/lz-string
```

**Comment by ktaroabobon** [comment]
埒があかないので技術調査

level1：
- typescript（^4）でライブラリが存在する
- typescriptでの書き方が載っている
- python（^3.10）でライブラリが存在する
- pythonでの書き方が載っている


level2:
- typescriptで実装可能
- pythonで実装可能

**Comment by ktaroabobon** [comment]
埒があかないので技術調査

level1：
- typescript（^4）でライブラリが存在する
- typescriptでの書き方が載っている
- python（^3.10）でライブラリが存在する
- pythonでの書き方が載っている


level2:
- typescriptで実装可能
- pythonで実装可能

**Comment by ktaroabobon** [comment]
- gzip: level1（tsで実装できない）

**Comment by ktaroabobon** [comment]
https://github.com/101arrowz/fflate

**Comment by ktaroabobon** [comment]
frontend
```typescript
const buf = fflate.strToU8(text);
// textをUint8Arrayに変換
const compressed = fflate.compressSync(buf, {level: 9});
// gzipをつかって圧縮
const compressedBlob = new Blob([compressed], {type: "application/gzip"});
const value = await compressedBlob.text();
// 圧縮した値をテキストとして保存
```

**Comment by ktaroabobon** [comment]
backend

```python
with target.open('rb') as f:
  original_data = f.read()
# バイナリとして文字を読む
compressed_data = gzip.compress(original_data)
# gzipを使って圧縮
compressed_base64_data = base64.b64encode(compressed_data)
# 圧縮した値をbase64でエンコードする
``

**Comment by ktaroabobon** [comment]
左：front側（typescript）
右：back側（python）

<img width="713" alt="image" src="https://user-images.githubusercontent.com/52523218/194803379-dee852fc-cb85-495e-86bb-bb80cf926c88.png">

**Comment by ktaroabobon** [comment]
https://github.com/Azure/azure-functions-python-worker/issues/415

**Comment by ktaroabobon** [comment]
[参考](https://github.com/Azure/azure-functions-python-worker/issues/415)

**Comment by ktaroabobon** [comment]
[pako](https://github.com/nodeca/pako)使ったらいけたっぽい

<img width="695" alt="image" src="https://user-images.githubusercontent.com/52523218/194841921-862b946a-2cae-4723-9262-482c32ce64ab.png">

**Comment by ktaroabobon** [comment]
https://qiita.com/mtoutside/items/cee708841cad7e02f85c

**Comment by ktaroabobon** [comment]
postの場合corsによってブロックされる

**Comment by ktaroabobon** [comment]
fastAPI側で変更した
https://fastapi.tiangolo.com/ja/tutorial/cors/

**Comment by ktaroabobon** [comment]
ローカルでは完了

**Comment by ktaroabobon** [comment]
production環境で行うためには、以下のことが必要

- [ ] 一旦no-authenticatedで行う
